function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=0;
    ys_(2)=0;
    ys_(3)=0;
    ys_(4)=0;
    ys_(5)=0;
    ys_(6)=0;
    ys_(7)=0;
    ys_(8)=0;
    ys_(9)=0;
    ys_(10)=0;
    ys_(11)=0;
    ys_(12)=0;
    ys_(13)=0;
    ys_(14)=0;
    ys_(15)=0;
    ys_(16)=0;
    ys_(17)=0;
    ys_(18)=0;
    ys_(19)=0;
    ys_(20)=0;
    ys_(21)=0;
    ys_(22)=0;
    ys_(23)=0;
    ys_(24)=0;
    ys_(25)=0;
    ys_(26)=0;
    ys_(27)=0;
    ys_(28)=0;
    ys_(29)=0;
    ys_(30)=0;
    % Auxiliary equations
end
